# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

use_frameworks!

target 'jabbr' do
	pod 'MMX'
	pod 'JSQMessagesViewController'
	pod 'GeotriggerSDK'
end

target 'jabbrTests' do

end

target 'jabbrUITests' do

end

